In [1]:
import os
import requests

# Base URL of Argo data index files
base_url = "https://data-argo.ifremer.fr/"

# List of main index files to download
files_to_download = [
    "ar_index_global_meta.txt.gz",
    "ar_index_global_prof.txt.gz",
    "ar_index_global_tech.txt.gz",
    "ar_index_global_traj.txt.gz",
    "ar_index_this_week_meta.txt",
    "ar_index_this_week_prof.txt",
    "argo_bio-profile_index.txt.gz",
    "argo_bio-traj_index.txt.gz",
    "argo_synthetic-profile_index.txt.gz"
]

# Folder to save downloads
download_folder = "argo_index_files"
os.makedirs(download_folder, exist_ok=True)

# Function to download a single file with retries
def download_file(url, local_path, retries=3):
    for attempt in range(retries):
        try:
            print(f"Downloading {url} ...")
            r = requests.get(url, stream=True, timeout=60)
            r.raise_for_status()
            with open(local_path, "wb") as f:
                for chunk in r.iter_content(chunk_size=1024*1024):
                    if chunk:
                        f.write(chunk)
            print(f"Downloaded: {local_path}")
            return True
        except Exception as e:
            print(f"Attempt {attempt+1} failed: {e}")
    print(f"Failed to download {url} after {retries} attempts.")
    return False

# Loop through all files
for file_name in files_to_download:
    file_url = base_url + file_name
    local_path = os.path.join(download_folder, file_name)

    # Skip if already exists
    if os.path.exists(local_path):
        print(f"Already exists: {file_name}, skipping.")
        continue

    download_file(file_url, local_path)

Downloading https://data-argo.ifremer.fr/ar_index_global_meta.txt.gz ...
Downloaded: argo_index_files/ar_index_global_meta.txt.gz
Downloading https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz ...
Downloaded: argo_index_files/ar_index_global_prof.txt.gz
Downloading https://data-argo.ifremer.fr/ar_index_global_tech.txt.gz ...
Downloaded: argo_index_files/ar_index_global_tech.txt.gz
Downloading https://data-argo.ifremer.fr/ar_index_global_traj.txt.gz ...
Downloaded: argo_index_files/ar_index_global_traj.txt.gz
Downloading https://data-argo.ifremer.fr/ar_index_this_week_meta.txt ...
Downloaded: argo_index_files/ar_index_this_week_meta.txt
Downloading https://data-argo.ifremer.fr/ar_index_this_week_prof.txt ...
Downloaded: argo_index_files/ar_index_this_week_prof.txt
Downloading https://data-argo.ifremer.fr/argo_bio-profile_index.txt.gz ...
Downloaded: argo_index_files/argo_bio-profile_index.txt.gz
Downloading https://data-argo.ifremer.fr/argo_bio-traj_index.txt.gz ...
Downloaded: argo_index_files/argo_bio-traj_index.txt.gz
Downloading https://data-argo.ifremer.fr/argo_synthetic-profile_index.txt.gz ...
Downloaded: argo_index_files/argo_synthetic-profile_index.txt.gz

In [2]:
import pandas as pd
import gzip
import os

gz_folder = "argo_index_files"
csv_folder = "index_files_csv"
os.makedirs(csv_folder, exist_ok=True)

for gz_file in os.listdir(gz_folder):
    if gz_file.endswith(".gz"):
        gz_path = os.path.join(gz_folder, gz_file)
        lines = []

        with gzip.open(gz_path, "rt") as f:
            for line in f:
                # Skip metadata/comment lines starting with #
                if line.startswith("#") or not line.strip():
                    continue
                # Split line by comma (assuming CSV format)
                parts = line.strip().split(",")
                lines.append(parts)

        # Create DataFrame using first row as column names
        if lines:
            df = pd.DataFrame(lines[1:], columns=lines[0])
        else:
            df = pd.DataFrame()  # empty file

        # Save CSV
        csv_file = os.path.join(csv_folder, gz_file.replace(".txt.gz", ".csv"))
        df.to_csv(csv_file, index=False)
        print(f"Converted {gz_file} → {csv_file}")

Converted argo_bio-profile_index.txt.gz → index_files_csv/argo_bio-profile_index.csv
Converted ar_index_global_traj.txt.gz → index_files_csv/ar_index_global_traj.csv
Converted ar_index_global_prof.txt.gz → index_files_csv/ar_index_global_prof.csv
Converted argo_bio-traj_index.txt.gz → index_files_csv/argo_bio-traj_index.csv
Converted ar_index_global_tech.txt.gz → index_files_csv/ar_index_global_tech.csv
Converted ar_index_global_meta.txt.gz → index_files_csv/ar_index_global_meta.csv
Converted argo_synthetic-profile_index.txt.gz → index_files_csv/argo_synthetic-profile_index.csv

In [3]:


# Download the zip file
files.download(zip_filename)

In [4]:
import pandas as pd
import os # Import the os module

path = "/content/index_files_csv/"
for file_name in os.listdir(path): # Iterate over the list of filenames
    file_path = os.path.join(path, file_name) # Get the full file path
    print(f"Processing file: {file_path}")
    df = pd.read_csv(file_path)
    display(df.head())
    print()

Processing file: /content/index_files_csv/argo_bio-profile_index.csv

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update
0,aoml/1900722/profiles/BD1900722_001.nc,2.006102e+13,-40.316,73.389,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
1,aoml/1900722/profiles/BD1900722_002.nc,2.006110e+13,-40.390,73.528,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
2,aoml/1900722/profiles/BD1900722_003.nc,2.006111e+13,-40.455,73.335,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
3,aoml/1900722/profiles/BD1900722_004.nc,2.006112e+13,-40.134,73.080,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230
4,aoml/1900722/profiles/BD1900722_005.nc,2.006120e+13,-39.641,73.158,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,20200312153230

Processing file: /content/index_files_csv/ar_index_global_prof.csv

,file,date,latitude,longitude,ocean,profiler_type,institution,date_update
0,aoml/13857/profiles/R13857_001.nc,1.997073e+13,0.267,-16.032,A,845,AO,20181011180520
1,aoml/13857/profiles/R13857_002.nc,1.997081e+13,0.072,-17.659,A,845,AO,20181011180521
2,aoml/13857/profiles/R13857_003.nc,1.997082e+13,0.543,-19.622,A,845,AO,20181011180521
3,aoml/13857/profiles/R13857_004.nc,1.997083e+13,1.256,-20.521,A,845,AO,20181011180521
4,aoml/13857/profiles/R13857_005.nc,1.997091e+13,0.720,-20.768,A,845,AO,20181011180521

Processing file: /content/index_files_csv/ar_index_global_traj.csv

,file,latitude_max,latitude_min,longitude_max,longitude_min,profiler_type,institution,date_update
0,aoml/13857/13857_Rtraj.nc,6.931,0.008,-15.014,-33.808,845.0,AO,20210428200335
1,aoml/13858/13858_Rtraj.nc,5.213,-0.363,-9.498,-17.793,845.0,AO,20210428200337
2,aoml/13859/13859_Rtraj.nc,5.929,-0.939,-18.642,-33.677,845.0,AO,20181011200025
3,aoml/15819/15819_Rtraj.nc,-2.659,-9.186,-16.427,-39.959,845.0,AO,20210428200342
4,aoml/15820/15820_Rtraj.nc,-1.978,-7.140,-9.896,-35.764,845.0,AO,20210428200346

Processing file: /content/index_files_csv/argo_synthetic-profile_index.csv

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update
0,aoml/1900722/profiles/SD1900722_001.nc,2.006102e+13,-40.316,73.389,I,846,AO,PRES TEMP PSAL DOXY,DDDD,20220628080801
1,aoml/1900722/profiles/SD1900722_002.nc,2.006110e+13,-40.390,73.528,I,846,AO,PRES TEMP PSAL DOXY,DDDD,20220628080813
2,aoml/1900722/profiles/SD1900722_003.nc,2.006111e+13,-40.455,73.335,I,846,AO,PRES TEMP PSAL DOXY,DDDD,20220628080826
3,aoml/1900722/profiles/SD1900722_004.nc,2.006112e+13,-40.134,73.080,I,846,AO,PRES TEMP PSAL DOXY,DDDD,20220628080839
4,aoml/1900722/profiles/SD1900722_005.nc,2.006120e+13,-39.641,73.158,I,846,AO,PRES TEMP PSAL DOXY,DDDD,20220628080852

Processing file: /content/index_files_csv/argo_bio-traj_index.csv

,file,latitude_max,latitude_min,longitude_max,longitude_min,profiler_type,institution,parameters,date_update
0,bodc/6904189/6904189_BRtraj.nc,NaN,NaN,NaN,NaN,836,BO,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,20240110013018
1,csio/2901550/2901550_BRtraj.nc,36.813,27.921,155.622,134.477,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,20241116060644
2,csio/2901551/2901551_BRtraj.nc,29.891,23.523,149.631,139.986,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,20241116060654
3,csio/2901552/2901552_BRtraj.nc,30.627,25.121,149.524,140.608,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,20241116060700
4,csio/2901553/2901553_BRtraj.nc,36.322,27.627,162.148,140.424,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,20241116060710

Processing file: /content/index_files_csv/ar_index_global_meta.csv

                       file  profiler_type institution     date_update
0  aoml/13857/13857_meta.nc          845.0          AO  20181011200014
1  aoml/13858/13858_meta.nc          845.0          AO  20181011200015
2  aoml/13859/13859_meta.nc          845.0          AO  20181011200025
3  aoml/15819/15819_meta.nc          845.0          AO  20181011200016
4  aoml/15820/15820_meta.nc          845.0          AO  20181011200018

Processing file: /content/index_files_csv/ar_index_global_tech.csv

                       file institution     date_update
0  aoml/13857/13857_tech.nc          AO  20210428200335
1  aoml/13858/13858_tech.nc          AO  20210428200337
2  aoml/13859/13859_tech.nc          AO  20181011200025
3  aoml/15819/15819_tech.nc          AO  20210428200342
4  aoml/15820/15820_tech.nc          AO  20210428200346

In [5]:
import pandas as pd
import os

path = "/content/index_files_csv/"
for file_name in os.listdir(path):
    file_path = os.path.join(path, file_name)
    print(f"Processing file: {file_path}")
    df = pd.read_csv(file_path)

    # Convert columns that likely contain date information to datetime, coercing errors
    for col in df.columns:
        if 'date' in col.lower() or 'update' in col.lower():
            df[col] = pd.to_datetime(df[col], errors='coerce')
            print(f"Converted column '{col}' to datetime.")

    display(df.head())
    print()

Processing file: /content/index_files_csv/argo_bio-profile_index.csv
Converted column 'date' to datetime.
Converted column 'date_update' to datetime.

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update
0,aoml/1900722/profiles/BD1900722_001.nc,1970-01-01 05:34:21.022021624,-40.316,73.389,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
1,aoml/1900722/profiles/BD1900722_002.nc,1970-01-01 05:34:21.101064423,-40.390,73.528,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
2,aoml/1900722/profiles/BD1900722_003.nc,1970-01-01 05:34:21.111101222,-40.455,73.335,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
3,aoml/1900722/profiles/BD1900722_004.nc,1970-01-01 05:34:21.121075021,-40.134,73.080,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
4,aoml/1900722/profiles/BD1900722_005.nc,1970-01-01 05:34:21.201183300,-39.641,73.158,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230

Processing file: /content/index_files_csv/ar_index_global_prof.csv
Converted column 'date' to datetime.
Converted column 'date_update' to datetime.

,file,date,latitude,longitude,ocean,profiler_type,institution,date_update
0,aoml/13857/profiles/R13857_001.nc,1970-01-01 05:32:50.729200300,0.267,-16.032,A,845,AO,1970-01-01 05:36:21.011180520
1,aoml/13857/profiles/R13857_002.nc,1970-01-01 05:32:50.809192112,0.072,-17.659,A,845,AO,1970-01-01 05:36:21.011180521
2,aoml/13857/profiles/R13857_003.nc,1970-01-01 05:32:50.820184545,0.543,-19.622,A,845,AO,1970-01-01 05:36:21.011180521
3,aoml/13857/profiles/R13857_004.nc,1970-01-01 05:32:50.831193905,1.256,-20.521,A,845,AO,1970-01-01 05:36:21.011180521
4,aoml/13857/profiles/R13857_005.nc,1970-01-01 05:32:50.911185808,0.720,-20.768,A,845,AO,1970-01-01 05:36:21.011180521

Processing file: /content/index_files_csv/ar_index_global_traj.csv
Converted column 'date_update' to datetime.

,file,latitude_max,latitude_min,longitude_max,longitude_min,profiler_type,institution,date_update
0,aoml/13857/13857_Rtraj.nc,6.931,0.008,-15.014,-33.808,845.0,AO,1970-01-01 05:36:50.428200335
1,aoml/13858/13858_Rtraj.nc,5.213,-0.363,-9.498,-17.793,845.0,AO,1970-01-01 05:36:50.428200337
2,aoml/13859/13859_Rtraj.nc,5.929,-0.939,-18.642,-33.677,845.0,AO,1970-01-01 05:36:21.011200025
3,aoml/15819/15819_Rtraj.nc,-2.659,-9.186,-16.427,-39.959,845.0,AO,1970-01-01 05:36:50.428200342
4,aoml/15820/15820_Rtraj.nc,-1.978,-7.140,-9.896,-35.764,845.0,AO,1970-01-01 05:36:50.428200346

Processing file: /content/index_files_csv/argo_synthetic-profile_index.csv
Converted column 'date' to datetime.
Converted column 'date_update' to datetime.

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update
0,aoml/1900722/profiles/SD1900722_001.nc,1970-01-01 05:34:21.022021624,-40.316,73.389,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080801
1,aoml/1900722/profiles/SD1900722_002.nc,1970-01-01 05:34:21.101064423,-40.390,73.528,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080813
2,aoml/1900722/profiles/SD1900722_003.nc,1970-01-01 05:34:21.111101222,-40.455,73.335,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080826
3,aoml/1900722/profiles/SD1900722_004.nc,1970-01-01 05:34:21.121075021,-40.134,73.080,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080839
4,aoml/1900722/profiles/SD1900722_005.nc,1970-01-01 05:34:21.201183300,-39.641,73.158,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080852

Processing file: /content/index_files_csv/argo_bio-traj_index.csv
Converted column 'date_update' to datetime.

,file,latitude_max,latitude_min,longitude_max,longitude_min,profiler_type,institution,parameters,date_update
0,bodc/6904189/6904189_BRtraj.nc,NaN,NaN,NaN,NaN,836,BO,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:20.110013018
1,csio/2901550/2901550_BRtraj.nc,36.813,27.921,155.622,134.477,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060644
2,csio/2901551/2901551_BRtraj.nc,29.891,23.523,149.631,139.986,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060654
3,csio/2901552/2901552_BRtraj.nc,30.627,25.121,149.524,140.608,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060700
4,csio/2901553/2901553_BRtraj.nc,36.322,27.627,162.148,140.424,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060710

Processing file: /content/index_files_csv/ar_index_global_meta.csv
Converted column 'date_update' to datetime.

,file,profiler_type,institution,date_update
0,aoml/13857/13857_meta.nc,845.0,AO,1970-01-01 05:36:21.011200014
1,aoml/13858/13858_meta.nc,845.0,AO,1970-01-01 05:36:21.011200015
2,aoml/13859/13859_meta.nc,845.0,AO,1970-01-01 05:36:21.011200025
3,aoml/15819/15819_meta.nc,845.0,AO,1970-01-01 05:36:21.011200016
4,aoml/15820/15820_meta.nc,845.0,AO,1970-01-01 05:36:21.011200018

Processing file: /content/index_files_csv/ar_index_global_tech.csv
Converted column 'date_update' to datetime.

                       file institution                   date_update
0  aoml/13857/13857_tech.nc          AO 1970-01-01 05:36:50.428200335
1  aoml/13858/13858_tech.nc          AO 1970-01-01 05:36:50.428200337
2  aoml/13859/13859_tech.nc          AO 1970-01-01 05:36:21.011200025
3  aoml/15819/15819_tech.nc          AO 1970-01-01 05:36:50.428200342
4  aoml/15820/15820_tech.nc          AO 1970-01-01 05:36:50.428200346

In [6]:
import pandas as pd
import os

path = "/content/index_files_csv/"
for file_name in os.listdir(path):
    file_path = os.path.join(path, file_name)
    print(f"Processing file: {file_path}")
    df = pd.read_csv(file_path)

    # Convert columns that likely contain date information to datetime, coercing errors
    for col in df.columns:
        if 'date' in col.lower() or 'update' in col.lower():
            df[col] = pd.to_datetime(df[col], errors='coerce')
            print(f"Converted column '{col}' to datetime in {file_name}.")

    # Save the updated DataFrame back to the original file
    df.to_csv(file_path, index=False)
    print(f"Saved updated data to {file_name}")
    print()

Processing file: /content/index_files_csv/argo_bio-profile_index.csv
Converted column 'date' to datetime in argo_bio-profile_index.csv.
Converted column 'date_update' to datetime in argo_bio-profile_index.csv.
Saved updated data to argo_bio-profile_index.csv

Processing file: /content/index_files_csv/ar_index_global_prof.csv
Converted column 'date' to datetime in ar_index_global_prof.csv.
Converted column 'date_update' to datetime in ar_index_global_prof.csv.
Saved updated data to ar_index_global_prof.csv

Processing file: /content/index_files_csv/ar_index_global_traj.csv
Converted column 'date_update' to datetime in ar_index_global_traj.csv.
Saved updated data to ar_index_global_traj.csv

Processing file: /content/index_files_csv/argo_synthetic-profile_index.csv
Converted column 'date' to datetime in argo_synthetic-profile_index.csv.
Converted column 'date_update' to datetime in argo_synthetic-profile_index.csv.
Saved updated data to argo_synthetic-profile_index.csv

Processing file: /content/index_files_csv/argo_bio-traj_index.csv
Converted column 'date_update' to datetime in argo_bio-traj_index.csv.
Saved updated data to argo_bio-traj_index.csv

Processing file: /content/index_files_csv/ar_index_global_meta.csv
Converted column 'date_update' to datetime in ar_index_global_meta.csv.
Saved updated data to ar_index_global_meta.csv

Processing file: /content/index_files_csv/ar_index_global_tech.csv
Converted column 'date_update' to datetime in ar_index_global_tech.csv.
Saved updated data to ar_index_global_tech.csv

In [7]:
import pandas as pd
import os # Import the os module

path = "/content/index_files_csv/"
for file_name in os.listdir(path): # Iterate over the list of filenames
    file_path = os.path.join(path, file_name) # Get the full file path
    print(f"Processing file: {file_path}")
    df = pd.read_csv(file_path)
    display(df.head())
    print()

Processing file: /content/index_files_csv/argo_bio-profile_index.csv

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update
0,aoml/1900722/profiles/BD1900722_001.nc,1970-01-01 05:34:21.022021624,-40.316,73.389,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
1,aoml/1900722/profiles/BD1900722_002.nc,1970-01-01 05:34:21.101064423,-40.390,73.528,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
2,aoml/1900722/profiles/BD1900722_003.nc,1970-01-01 05:34:21.111101222,-40.455,73.335,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
3,aoml/1900722/profiles/BD1900722_004.nc,1970-01-01 05:34:21.121075021,-40.134,73.080,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230
4,aoml/1900722/profiles/BD1900722_005.nc,1970-01-01 05:34:21.201183300,-39.641,73.158,I,846,AO,PRES TEMP_DOXY BPHASE_DOXY DOXY,RRRD,1970-01-01 05:36:40.312153230

Processing file: /content/index_files_csv/ar_index_global_prof.csv

,file,date,latitude,longitude,ocean,profiler_type,institution,date_update
0,aoml/13857/profiles/R13857_001.nc,1970-01-01 05:32:50.729200300,0.267,-16.032,A,845,AO,1970-01-01 05:36:21.011180520
1,aoml/13857/profiles/R13857_002.nc,1970-01-01 05:32:50.809192112,0.072,-17.659,A,845,AO,1970-01-01 05:36:21.011180521
2,aoml/13857/profiles/R13857_003.nc,1970-01-01 05:32:50.820184545,0.543,-19.622,A,845,AO,1970-01-01 05:36:21.011180521
3,aoml/13857/profiles/R13857_004.nc,1970-01-01 05:32:50.831193905,1.256,-20.521,A,845,AO,1970-01-01 05:36:21.011180521
4,aoml/13857/profiles/R13857_005.nc,1970-01-01 05:32:50.911185808,0.720,-20.768,A,845,AO,1970-01-01 05:36:21.011180521

Processing file: /content/index_files_csv/ar_index_global_traj.csv

,file,latitude_max,latitude_min,longitude_max,longitude_min,profiler_type,institution,date_update
0,aoml/13857/13857_Rtraj.nc,6.931,0.008,-15.014,-33.808,845.0,AO,1970-01-01 05:36:50.428200335
1,aoml/13858/13858_Rtraj.nc,5.213,-0.363,-9.498,-17.793,845.0,AO,1970-01-01 05:36:50.428200337
2,aoml/13859/13859_Rtraj.nc,5.929,-0.939,-18.642,-33.677,845.0,AO,1970-01-01 05:36:21.011200025
3,aoml/15819/15819_Rtraj.nc,-2.659,-9.186,-16.427,-39.959,845.0,AO,1970-01-01 05:36:50.428200342
4,aoml/15820/15820_Rtraj.nc,-1.978,-7.140,-9.896,-35.764,845.0,AO,1970-01-01 05:36:50.428200346

Processing file: /content/index_files_csv/argo_synthetic-profile_index.csv

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update
0,aoml/1900722/profiles/SD1900722_001.nc,1970-01-01 05:34:21.022021624,-40.316,73.389,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080801
1,aoml/1900722/profiles/SD1900722_002.nc,1970-01-01 05:34:21.101064423,-40.390,73.528,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080813
2,aoml/1900722/profiles/SD1900722_003.nc,1970-01-01 05:34:21.111101222,-40.455,73.335,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080826
3,aoml/1900722/profiles/SD1900722_004.nc,1970-01-01 05:34:21.121075021,-40.134,73.080,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080839
4,aoml/1900722/profiles/SD1900722_005.nc,1970-01-01 05:34:21.201183300,-39.641,73.158,I,846,AO,PRES TEMP PSAL DOXY,DDDD,1970-01-01 05:37:00.628080852

Processing file: /content/index_files_csv/argo_bio-traj_index.csv

,file,latitude_max,latitude_min,longitude_max,longitude_min,profiler_type,institution,parameters,date_update
0,bodc/6904189/6904189_BRtraj.nc,NaN,NaN,NaN,NaN,836,BO,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:20.110013018
1,csio/2901550/2901550_BRtraj.nc,36.813,27.921,155.622,134.477,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060644
2,csio/2901551/2901551_BRtraj.nc,29.891,23.523,149.631,139.986,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060654
3,csio/2901552/2901552_BRtraj.nc,30.627,25.121,149.524,140.608,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060700
4,csio/2901553/2901553_BRtraj.nc,36.322,27.627,162.148,140.424,841,HZ,PRES C1PHASE_DOXY C2PHASE_DOXY TEMP_DOXY DOXY ...,1970-01-01 05:37:21.116060710

Processing file: /content/index_files_csv/ar_index_global_meta.csv

,file,profiler_type,institution,date_update
0,aoml/13857/13857_meta.nc,845.0,AO,1970-01-01 05:36:21.011200014
1,aoml/13858/13858_meta.nc,845.0,AO,1970-01-01 05:36:21.011200015
2,aoml/13859/13859_meta.nc,845.0,AO,1970-01-01 05:36:21.011200025
3,aoml/15819/15819_meta.nc,845.0,AO,1970-01-01 05:36:21.011200016
4,aoml/15820/15820_meta.nc,845.0,AO,1970-01-01 05:36:21.011200018

Processing file: /content/index_files_csv/ar_index_global_tech.csv

                       file institution                    date_update
0  aoml/13857/13857_tech.nc          AO  1970-01-01 05:36:50.428200335
1  aoml/13858/13858_tech.nc          AO  1970-01-01 05:36:50.428200337
2  aoml/13859/13859_tech.nc          AO  1970-01-01 05:36:21.011200025
3  aoml/15819/15819_tech.nc          AO  1970-01-01 05:36:50.428200342
4  aoml/15820/15820_tech.nc          AO  1970-01-01 05:36:50.428200346

In [ ]:
import shutil
import os
from google.colab import files

folder_to_zip = '/content/index_files_csv'
zip_filename = 'index_files_csv.zip'

# Create a zip archive of the folder
shutil.make_archive(zip_filename.replace('.zip', ''), 'zip', folder_to_zip)

In [8]:
global_prof = pd.read_csv("/content/index_files_csv/ar_index_global_prof.csv")
global_prof.head()

,file,date,latitude,longitude,ocean,profiler_type,institution,date_update
0,aoml/13857/profiles/R13857_001.nc,1970-01-01 05:32:50.729200300,0.267,-16.032,A,845,AO,1970-01-01 05:36:21.011180520
1,aoml/13857/profiles/R13857_002.nc,1970-01-01 05:32:50.809192112,0.072,-17.659,A,845,AO,1970-01-01 05:36:21.011180521
2,aoml/13857/profiles/R13857_003.nc,1970-01-01 05:32:50.820184545,0.543,-19.622,A,845,AO,1970-01-01 05:36:21.011180521
3,aoml/13857/profiles/R13857_004.nc,1970-01-01 05:32:50.831193905,1.256,-20.521,A,845,AO,1970-01-01 05:36:21.011180521
4,aoml/13857/profiles/R13857_005.nc,1970-01-01 05:32:50.911185808,0.720,-20.768,A,845,AO,1970-01-01 05:36:21.011180521

In [9]:
global_prof.shape

(3217181, 8)

In [10]:
# Assuming 'global_prof' DataFrame is already loaded and available
if 'global_prof' in locals() and isinstance(global_prof, pd.DataFrame):
    ocean_i_count = global_prof[global_prof['ocean'] == 'I'].shape[0]
    print(f"The count of rows where 'ocean' is 'I' in global_prof is: {ocean_i_count}")
else:
    print("The 'global_prof' DataFrame is not available.")

The count of rows where 'ocean' is 'I' in global_prof is: 615977

In [ ]:
import os
import pandas as pd
import requests

# Folders
index_folder = "index_files_csv"
download_folder = "dac_downloads"
os.makedirs(download_folder, exist_ok=True)

# Base URL for DAC files
base_url = "https://data-argo.ifremer.fr/dac/"

# 1️⃣ Load global profile CSV
prof_csv = os.path.join(index_folder, "ar_index_global_prof.csv")
prof_df = pd.read_csv(prof_csv)

# 2️⃣ Load DAC metadata CSV (optional, for extra info)
meta_csv = os.path.join(index_folder, "ar_index_global_meta.csv")
meta_df = pd.read_csv(meta_csv)

# 3️⃣ Filter for Indian Ocean floats using 'ocean' column
indian_ocean_df = prof_df[prof_df['ocean'] == 'I']

# Optional: merge with meta to get extra info if needed
# indian_ocean_df = indian_ocean_df.merge(meta_df, on='platform_number', how='left')

print(f"Number of Indian Ocean profiles: {len(indian_ocean_df)}")

# 4️⃣ Function to download NetCDF file with retry
def download_file(url, local_path, retries=3):
    for attempt in range(retries):
        try:
            print(f"Downloading {url} ...")
            r = requests.get(url, stream=True, timeout=60)
            r.raise_for_status()
            with open(local_path, "wb") as f:
                for chunk in r.iter_content(chunk_size=1024*1024):
                    if chunk:
                        f.write(chunk)
            print(f"Downloaded: {local_path}")
            return True
        except Exception as e:
            print(f"Attempt {attempt+1} failed: {e}")
    print(f"Failed to download {url}")
    return False

# 5️⃣ Download Indian Ocean profiles
for dac_path in indian_ocean_df['file']:
    file_url = base_url + dac_path
    local_file = os.path.join(download_folder, os.path.basename(dac_path))

    # Skip if already downloaded
    if os.path.exists(local_file):
        continue

    download_file(file_url, local_file)

Number of Indian Ocean profiles: 615977
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_001.nc ...
Downloaded: dac_downloads/D1900042_001.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_002.nc ...
Downloaded: dac_downloads/D1900042_002.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_003.nc ...
Downloaded: dac_downloads/D1900042_003.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_004.nc ...
Downloaded: dac_downloads/D1900042_004.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_005.nc ...
Downloaded: dac_downloads/D1900042_005.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_006.nc ...
Downloaded: dac_downloads/D1900042_006.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_007.nc ...
Downloaded: dac_downloads/D1900042_007.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_008.nc ...
Downloaded: dac_downloads/D1900042_008.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_009.nc ...
Downloaded: dac_downloads/D1900042_009.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_010.nc ...
Downloaded: dac_downloads/D1900042_010.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_011.nc ...
Downloaded: dac_downloads/D1900042_011.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_012.nc ...
Downloaded: dac_downloads/D1900042_012.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_013.nc ...
Downloaded: dac_downloads/D1900042_013.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_014.nc ...
Downloaded: dac_downloads/D1900042_014.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_015.nc ...
Downloaded: dac_downloads/D1900042_015.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_016.nc ...
Downloaded: dac_downloads/D1900042_016.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_017.nc ...
Downloaded: dac_downloads/D1900042_017.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_018.nc ...
Downloaded: dac_downloads/D1900042_018.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_019.nc ...
Downloaded: dac_downloads/D1900042_019.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_020.nc ...
Downloaded: dac_downloads/D1900042_020.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_021.nc ...
Downloaded: dac_downloads/D1900042_021.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_022.nc ...
Downloaded: dac_downloads/D1900042_022.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_023.nc ...
Downloaded: dac_downloads/D1900042_023.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_024.nc ...
Downloaded: dac_downloads/D1900042_024.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_025.nc ...
Downloaded: dac_downloads/D1900042_025.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_026.nc ...
Downloaded: dac_downloads/D1900042_026.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_027.nc ...
Downloaded: dac_downloads/D1900042_027.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_028.nc ...
Downloaded: dac_downloads/D1900042_028.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_029.nc ...
Downloaded: dac_downloads/D1900042_029.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_030.nc ...
Downloaded: dac_downloads/D1900042_030.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_031.nc ...
Downloaded: dac_downloads/D1900042_031.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_032.nc ...
Downloaded: dac_downloads/D1900042_032.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_033.nc ...
Downloaded: dac_downloads/D1900042_033.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_034.nc ...
Downloaded: dac_downloads/D1900042_034.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_035.nc ...
Downloaded: dac_downloads/D1900042_035.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_036.nc ...
Downloaded: dac_downloads/D1900042_036.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_037.nc ...
Downloaded: dac_downloads/D1900042_037.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_038.nc ...
Downloaded: dac_downloads/D1900042_038.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_039.nc ...
Downloaded: dac_downloads/D1900042_039.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_040.nc ...
Downloaded: dac_downloads/D1900042_040.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_041.nc ...
Downloaded: dac_downloads/D1900042_041.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_042.nc ...
Downloaded: dac_downloads/D1900042_042.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_043.nc ...
Downloaded: dac_downloads/D1900042_043.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_044.nc ...
Downloaded: dac_downloads/D1900042_044.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_045.nc ...
Downloaded: dac_downloads/D1900042_045.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_046.nc ...
Downloaded: dac_downloads/D1900042_046.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_047.nc ...
Downloaded: dac_downloads/D1900042_047.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_048.nc ...
Downloaded: dac_downloads/D1900042_048.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_049.nc ...
Downloaded: dac_downloads/D1900042_049.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_050.nc ...
Downloaded: dac_downloads/D1900042_050.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_051.nc ...
Downloaded: dac_downloads/D1900042_051.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_052.nc ...
Downloaded: dac_downloads/D1900042_052.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_053.nc ...
Downloaded: dac_downloads/D1900042_053.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_054.nc ...
Downloaded: dac_downloads/D1900042_054.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_055.nc ...
Downloaded: dac_downloads/D1900042_055.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_056.nc ...
Downloaded: dac_downloads/D1900042_056.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_057.nc ...
Downloaded: dac_downloads/D1900042_057.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_058.nc ...
Downloaded: dac_downloads/D1900042_058.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_059.nc ...
Downloaded: dac_downloads/D1900042_059.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_060.nc ...
Downloaded: dac_downloads/D1900042_060.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_061.nc ...
Downloaded: dac_downloads/D1900042_061.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_062.nc ...
Downloaded: dac_downloads/D1900042_062.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_063.nc ...
Downloaded: dac_downloads/D1900042_063.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_064.nc ...
Downloaded: dac_downloads/D1900042_064.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_065.nc ...
Downloaded: dac_downloads/D1900042_065.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_066.nc ...
Downloaded: dac_downloads/D1900042_066.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_067.nc ...
Downloaded: dac_downloads/D1900042_067.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_068.nc ...
Downloaded: dac_downloads/D1900042_068.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_069.nc ...
Downloaded: dac_downloads/D1900042_069.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_070.nc ...
Downloaded: dac_downloads/D1900042_070.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_071.nc ...
Downloaded: dac_downloads/D1900042_071.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_072.nc ...
Downloaded: dac_downloads/D1900042_072.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_073.nc ...
Downloaded: dac_downloads/D1900042_073.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_074.nc ...
Downloaded: dac_downloads/D1900042_074.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_075.nc ...
Downloaded: dac_downloads/D1900042_075.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_076.nc ...
Downloaded: dac_downloads/D1900042_076.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_077.nc ...
Downloaded: dac_downloads/D1900042_077.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_078.nc ...
Downloaded: dac_downloads/D1900042_078.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_079.nc ...
Downloaded: dac_downloads/D1900042_079.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_080.nc ...
Downloaded: dac_downloads/D1900042_080.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_081.nc ...
Downloaded: dac_downloads/D1900042_081.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_082.nc ...
Downloaded: dac_downloads/D1900042_082.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_083.nc ...
Downloaded: dac_downloads/D1900042_083.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_084.nc ...
Downloaded: dac_downloads/D1900042_084.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_085.nc ...
Downloaded: dac_downloads/D1900042_085.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_086.nc ...
Downloaded: dac_downloads/D1900042_086.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_087.nc ...
Downloaded: dac_downloads/D1900042_087.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_088.nc ...
Downloaded: dac_downloads/D1900042_088.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_089.nc ...
Downloaded: dac_downloads/D1900042_089.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_090.nc ...
Downloaded: dac_downloads/D1900042_090.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_091.nc ...
Downloaded: dac_downloads/D1900042_091.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_092.nc ...
Downloaded: dac_downloads/D1900042_092.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_093.nc ...
Downloaded: dac_downloads/D1900042_093.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_094.nc ...
Downloaded: dac_downloads/D1900042_094.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_095.nc ...
Downloaded: dac_downloads/D1900042_095.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_096.nc ...
Downloaded: dac_downloads/D1900042_096.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_097.nc ...
Downloaded: dac_downloads/D1900042_097.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_098.nc ...
Downloaded: dac_downloads/D1900042_098.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_099.nc ...
Downloaded: dac_downloads/D1900042_099.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_100.nc ...
Downloaded: dac_downloads/D1900042_100.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_101.nc ...
Downloaded: dac_downloads/D1900042_101.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_102.nc ...
Downloaded: dac_downloads/D1900042_102.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_103.nc ...
Downloaded: dac_downloads/D1900042_103.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_104.nc ...
Downloaded: dac_downloads/D1900042_104.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_105.nc ...
Downloaded: dac_downloads/D1900042_105.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_106.nc ...
Downloaded: dac_downloads/D1900042_106.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_107.nc ...
Downloaded: dac_downloads/D1900042_107.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_108.nc ...
Downloaded: dac_downloads/D1900042_108.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_109.nc ...
Downloaded: dac_downloads/D1900042_109.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_110.nc ...
Downloaded: dac_downloads/D1900042_110.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_111.nc ...
Downloaded: dac_downloads/D1900042_111.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_112.nc ...
Downloaded: dac_downloads/D1900042_112.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_113.nc ...
Downloaded: dac_downloads/D1900042_113.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_114.nc ...
Downloaded: dac_downloads/D1900042_114.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_115.nc ...
Downloaded: dac_downloads/D1900042_115.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_116.nc ...
Downloaded: dac_downloads/D1900042_116.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_117.nc ...
Downloaded: dac_downloads/D1900042_117.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_118.nc ...
Downloaded: dac_downloads/D1900042_118.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_119.nc ...
Downloaded: dac_downloads/D1900042_119.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900042/profiles/D1900042_120.nc ...
Downloaded: dac_downloads/D1900042_120.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_001.nc ...
Downloaded: dac_downloads/D1900043_001.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_002.nc ...
Downloaded: dac_downloads/D1900043_002.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_003.nc ...
Downloaded: dac_downloads/D1900043_003.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_004.nc ...
Downloaded: dac_downloads/D1900043_004.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_005.nc ...
Downloaded: dac_downloads/D1900043_005.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_006.nc ...
Downloaded: dac_downloads/D1900043_006.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_007.nc ...
Downloaded: dac_downloads/D1900043_007.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_008.nc ...
Downloaded: dac_downloads/D1900043_008.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_009.nc ...
Downloaded: dac_downloads/D1900043_009.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_010.nc ...
Downloaded: dac_downloads/D1900043_010.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_011.nc ...
Downloaded: dac_downloads/D1900043_011.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_012.nc ...
Downloaded: dac_downloads/D1900043_012.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_013.nc ...
Downloaded: dac_downloads/D1900043_013.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_014.nc ...
Downloaded: dac_downloads/D1900043_014.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_015.nc ...
Downloaded: dac_downloads/D1900043_015.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_016.nc ...
Downloaded: dac_downloads/D1900043_016.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_017.nc ...
Downloaded: dac_downloads/D1900043_017.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_018.nc ...
Downloaded: dac_downloads/D1900043_018.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_019.nc ...
Downloaded: dac_downloads/D1900043_019.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_020.nc ...
Downloaded: dac_downloads/D1900043_020.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_021.nc ...
Downloaded: dac_downloads/D1900043_021.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_022.nc ...
Downloaded: dac_downloads/D1900043_022.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_023.nc ...
Downloaded: dac_downloads/D1900043_023.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_024.nc ...
Downloaded: dac_downloads/D1900043_024.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_025.nc ...
Downloaded: dac_downloads/D1900043_025.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_026.nc ...
Downloaded: dac_downloads/D1900043_026.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_027.nc ...
Downloaded: dac_downloads/D1900043_027.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_028.nc ...
Downloaded: dac_downloads/D1900043_028.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_029.nc ...
Downloaded: dac_downloads/D1900043_029.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_030.nc ...
Downloaded: dac_downloads/D1900043_030.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_031.nc ...
Downloaded: dac_downloads/D1900043_031.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_032.nc ...
Downloaded: dac_downloads/D1900043_032.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_033.nc ...
Downloaded: dac_downloads/D1900043_033.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_034.nc ...
Downloaded: dac_downloads/D1900043_034.nc
Downloading https://data-argo.ifremer.fr/dac/aoml/1900043/profiles/D1900043_035.nc ...